openapi: '3.0.3'

required:
  - id
  - name
  - description
  - price
  - amount
  - category

properties:
  id:
    type: string
    format: uuid
  name:
    type: string
  description:
    type: string
  price:
    type: number
    format: double
  amount:
    type: number
    format: double
  category:
    $ref: './categories/CategoryDto.yaml'
